#  Name of input file containing fiber photometry data (string)
input_filename: "SynchronyData/FiberPhoSig2020-10-12T15_30_41.csv"

#  Name you'd like for the output CSV file. Should include
# file path if different than current file (string)
output_filename: "T15_30_41"

#  Number of the animal corresponding to fluoresence data (int)
animal_ID: "1234" 

# Date of exp/date data was gathered (string, form: YYYY-MM-DD)           
exp_date: "2020-11-22" 

# Brief explantation of experiment (string)
exp_desc: "synchrony test"

# To plot the raw signal trace, set True (otherwise False)
plot_raw_signal: False

# To plot the isosbestic fit, set True (otherwise False)
plot_iso_fit: False